[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
evm_version = "london"
solc = "0.8.27"
optimizer = true
optimizer_runs = 200
block_gas_limit = 15000000
verbosity=2

[rpc_endpoints]
flare = "${FLARE_RPC_URL}"
coston2 = "${COSTON2_RPC_URL}"

[etherscan]
flare = { key = "${FLARESCAN_API_KEY}", chain = 14, url = "${FLARE_FLARESCAN_URL}" }
coston2 = { key = "${FLARESCAN_API_KEY}", chain = 114, url = "${COSTON2_FLARESCAN_URL}" }

[fmt]
sort_imports=true